export interface ViralContentEntry {
  id: string;
  title: string;
  niche: string[];
  topic: string;
  hookType: string;
  hook: string;
  storytellingPattern: string;
  contentStructure: string;
  keyInsight: string;
  viralFactor: string;
  estimatedViews: string;
  tone: string[];
}

export const VIRAL_CONTENT: ViralContentEntry[] = [
  // ── Finance / Investing ──────────────────────────────────────
  {
    id: "vc_fin_001",
    title: "I Invested $1,000 Every Month for 10 Years — Here's What Happened",
    niche: ["finance", "investing", "personal finance", "wealth building"],
    topic: "long-term investing",
    hookType: "personal story with specific number",
    hook: "10 years ago I started investing exactly $1,000 every single month. Here's the exact portfolio value today.",
    storytellingPattern: "personal experiment + reveal",
    contentStructure: "personal story → monthly breakdown → compound growth reveal → actionable steps for viewers",
    keyInsight: "Specific numbers + time + personal story = maximum credibility and curiosity",
    viralFactor: "Exact numbers make abstract concepts concrete; viewers identify with a normal person doing this",
    estimatedViews: "15M+",
    tone: ["educational", "motivational", "honest"],
  },
  {
    id: "vc_fin_002",
    title: "The Financial Advice Nobody Tells You Until It's Too Late",
    niche: ["finance", "personal finance", "money", "wealth"],
    topic: "financial mistakes",
    hookType: "secret / forbidden knowledge",
    hook: "The thing that took me from broke to financially free was never taught in school. In fact, most people learn it the hard way.",
    storytellingPattern: "secret reveal + contrast (before/after)",
    contentStructure: "hook → why this is hidden → the truth → case studies → call to action",
    keyInsight: "People are wired to seek forbidden or hidden knowledge — 'secret' framing massively boosts curiosity gap",
    viralFactor: "Positioned against the establishment (school, parents, financial advisors) which resonates with disenchanted viewers",
    estimatedViews: "20M+",
    tone: ["provocative", "educational", "empowering"],
  },
  {
    id: "vc_fin_003",
    title: "Living on $30 a Day in the World's Most Expensive City",
    niche: ["finance", "frugal living", "budgeting", "lifestyle"],
    topic: "extreme budgeting",
    hookType: "challenge / experiment",
    hook: "I spent one week in New York City on only $30 per day. Most people said it was impossible.",
    storytellingPattern: "challenge narrative with day-by-day structure",
    contentStructure: "setup the challenge → daily vlog-style breakdown → final tallies → tips extracted",
    keyInsight: "Extreme constraints create inherent drama; viewers watch to see if it's possible",
    viralFactor: "Relatability (everyone wants to save money) + shock (extreme constraint) + practical takeaways",
    estimatedViews: "8M+",
    tone: ["entertaining", "educational", "relatable"],
  },

  // ── Health / Fitness ─────────────────────────────────────────
  {
    id: "vc_fit_001",
    title: "I Worked Out Every Single Day for 365 Days — My Honest Results",
    niche: ["fitness", "health", "workout", "body transformation"],
    topic: "fitness consistency",
    hookType: "long-term experiment reveal",
    hook: "365 days. No rest days. No excuses. Here's exactly what happened to my body, my mind, and my life.",
    storytellingPattern: "year-long journey with milestone reveals",
    contentStructure: "day 1 footage → monthly check-ins → day 365 reveal → what I learned → what actually matters",
    keyInsight: "Long-term commitment videos create a before/after tension that keeps viewers watching for the reveal",
    viralFactor: "Aspirational + time-compression (1 year in 15 minutes) + honest failure moments create authenticity",
    estimatedViews: "25M+",
    tone: ["motivational", "honest", "inspiring"],
  },
  {
    id: "vc_fit_002",
    title: "Doctors Don't Want You to Know This About Weight Loss",
    niche: ["health", "fitness", "weight loss", "nutrition"],
    topic: "weight loss myths",
    hookType: "controversy / anti-establishment",
    hook: "Everything you've been told about losing weight is designed to keep you coming back. Here's the truth they don't want you to know.",
    storytellingPattern: "myth-busting with evidence",
    contentStructure: "controversial claim → why mainstream gets it wrong → evidence → the actual solution → simple action plan",
    keyInsight: "Anti-establishment framing triggers emotion and sharing; people feel they're getting insider information",
    viralFactor: "Outrage bait (doctors hiding truth) + hopeful resolution = high completion and share rate",
    estimatedViews: "12M+",
    tone: ["provocative", "educational", "empowering"],
  },
  {
    id: "vc_fit_003",
    title: "I Ate Only McDonald's for 30 Days — What Happened to My Health",
    niche: ["health", "nutrition", "food", "experiment"],
    topic: "fast food experiment",
    hookType: "shocking experiment",
    hook: "Breakfast, lunch, and dinner at McDonald's. Every. Single. Day. For 30 days straight. My doctor was horrified.",
    storytellingPattern: "experiment narrative with expert reactions",
    contentStructure: "setup + doctor warning → weekly check-ins with bloodwork → final results → the data + what it means",
    keyInsight: "Experiments viewers would never do themselves get massive vicarious curiosity",
    viralFactor: "Taboo premise + legitimate data + doctor reactions add credibility to sensational premise",
    estimatedViews: "18M+",
    tone: ["entertaining", "educational", "shocking"],
  },

  // ── Technology / AI ──────────────────────────────────────────
  {
    id: "vc_tech_001",
    title: "AI Will Replace Your Job in 2025 — Unless You Do This",
    niche: ["technology", "AI", "career", "future of work"],
    topic: "AI job displacement",
    hookType: "fear + solution",
    hook: "Millions of jobs will disappear in the next 18 months. I'm going to show you exactly which ones and what to do about it.",
    storytellingPattern: "threat → specific evidence → actionable escape route",
    contentStructure: "alarming stat → which jobs are at risk → the jobs that are safe → what skills to build → specific action plan",
    keyInsight: "Fear is a powerful motivator; pairing it with actionable hope creates extremely high retention",
    viralFactor: "Existential threat (livelihood) + specific timeline + practical solution = massive share rate",
    estimatedViews: "30M+",
    tone: ["alarming", "educational", "empowering"],
  },
  {
    id: "vc_tech_002",
    title: "I Built a $10,000/Month Business Using Only AI Tools",
    niche: ["technology", "AI", "entrepreneurship", "passive income"],
    topic: "AI business building",
    hookType: "income claim with AI angle",
    hook: "Last month I made $10,847 without writing a single line of code, hiring anyone, or working more than 4 hours a day. Here's the exact system.",
    storytellingPattern: "income reveal + system breakdown",
    contentStructure: "income proof → the business model → each AI tool used → exact workflow → how to replicate it",
    keyInsight: "Specific numbers + AI novelty + low barrier to entry makes viewers believe they can replicate it",
    viralFactor: "Dream lifestyle (income + freedom) + accessible technology + proof = aspirational motivation",
    estimatedViews: "22M+",
    tone: ["motivational", "educational", "aspirational"],
  },

  // ── Self-Improvement / Productivity ─────────────────────────
  {
    id: "vc_self_001",
    title: "I Woke Up at 5 AM Every Day for a Year — Here's What Nobody Tells You",
    niche: ["self-improvement", "productivity", "habits", "morning routine"],
    topic: "morning routine",
    hookType: "long-term experiment with honest twist",
    hook: "Every productivity guru tells you to wake up at 5 AM. I did it for a full year. The results were not what I expected.",
    storytellingPattern: "expectation subversion + honest reporting",
    contentStructure: "why I tried it → first month struggles → what changed → what they don't tell you → the real verdict",
    keyInsight: "Subverting viewer expectations (not a 'it changed my life' video) creates authenticity and trust",
    viralFactor: "Counter-narrative to popular advice gets shared by skeptics AND believers; honest takes drive trust",
    estimatedViews: "14M+",
    tone: ["honest", "educational", "relatable"],
  },
  {
    id: "vc_self_002",
    title: "The Dark Side of Discipline No One Talks About",
    niche: ["self-improvement", "mental health", "productivity", "psychology"],
    topic: "toxic productivity",
    hookType: "taboo perspective",
    hook: "Discipline is destroying people's lives. I know because it nearly destroyed mine.",
    storytellingPattern: "personal confession + counterintuitive insight",
    contentStructure: "shocking opening statement → personal story → the hidden cost of extreme discipline → the balance → healthier framework",
    keyInsight: "Going against the dominant narrative in a community (productivity) generates debate and high engagement",
    viralFactor: "Taboo in the self-improvement community + vulnerable personal story = authenticity magnet",
    estimatedViews: "9M+",
    tone: ["honest", "vulnerable", "thought-provoking"],
  },
  {
    id: "vc_self_003",
    title: "Read 52 Books in a Year — What I Actually Learned",
    niche: ["self-improvement", "education", "habits", "reading"],
    topic: "reading challenge",
    hookType: "achievement reveal with honest assessment",
    hook: "I read one book per week for an entire year. 52 books total. Honestly? Most of them were a waste of time.",
    storytellingPattern: "achievement + contrarian takeaway",
    contentStructure: "the challenge → best books ranked → worst books (controversial) → what actually changes from reading → the truth about knowledge",
    keyInsight: "Admitting a popular goal might be overrated gives credibility and generates discussion",
    viralFactor: "Aspirational achievement + controversial verdict drives comments and shares from both sides",
    estimatedViews: "7M+",
    tone: ["educational", "honest", "thought-provoking"],
  },

  // ── Business / Entrepreneurship ──────────────────────────────
  {
    id: "vc_biz_001",
    title: "How I Started a Business With $0 and Made $100K in 6 Months",
    niche: ["business", "entrepreneurship", "startup", "side hustle"],
    topic: "zero-cost business",
    hookType: "zero-to-success story",
    hook: "Six months ago I had $0, no connections, and no business experience. Today my business did $100,000. Here's exactly how.",
    storytellingPattern: "rags-to-riches with step-by-step breakdown",
    contentStructure: "starting point (zero) → the idea → first sale story → scaling decisions → month-by-month revenue → exact framework",
    keyInsight: "The 'starting from zero' angle removes the 'I need capital' excuse — democratizes entrepreneurship",
    viralFactor: "Specific numbers + zero barrier narrative + step-by-step replication = massive aspiration trigger",
    estimatedViews: "19M+",
    tone: ["motivational", "educational", "inspiring"],
  },
  {
    id: "vc_biz_002",
    title: "Why Most Small Businesses Fail in Their First Year (It's Not What You Think)",
    niche: ["business", "entrepreneurship", "startups", "money"],
    topic: "business failure",
    hookType: "contrarian insight",
    hook: "90% of small businesses fail within the first year. Everyone says it's because they run out of money. They're wrong.",
    storytellingPattern: "conventional wisdom debunked + real reason revealed",
    contentStructure: "the statistic → the common explanation → why that's wrong → the real reason → how to avoid it",
    keyInsight: "Challenging a widely-cited fact creates intellectual curiosity and positions creator as having insider knowledge",
    viralFactor: "Contrarian take on a scary stat + actionable insight = every entrepreneur shares this as a warning",
    estimatedViews: "11M+",
    tone: ["educational", "provocative", "practical"],
  },

  // ── True Crime / Mystery ─────────────────────────────────────
  {
    id: "vc_crime_001",
    title: "The Murder Case That Baffled Police for 20 Years — Finally Solved",
    niche: ["true crime", "mystery", "cold case", "investigation"],
    topic: "cold case solved",
    hookType: "resolution of long-standing mystery",
    hook: "For 20 years, detectives had no answers. Then one small detail changed everything. This is the case that haunted an entire town.",
    storytellingPattern: "mystery setup → investigation journey → breakthrough moment → resolution",
    contentStructure: "the crime → the investigation failures → the cold case years → the breakthrough → the reveal → aftermath",
    keyInsight: "The longer a case went unsolved, the more satisfying the resolution — time amplifies the payoff",
    viralFactor: "Built-in mystery narrative structure + real events + emotional resolution = binge-watching trigger",
    estimatedViews: "16M+",
    tone: ["dramatic", "investigative", "emotional"],
  },

  // ── History ─────────────────────────────────────────────────
  {
    id: "vc_hist_001",
    title: "The Ancient Civilization That Was More Advanced Than We Thought",
    niche: ["history", "archaeology", "ancient civilizations", "mystery"],
    topic: "lost civilization",
    hookType: "knowledge gap + discovery",
    hook: "Historians got it completely wrong. This civilization, which we thought was primitive, had technology we don't fully understand even today.",
    storytellingPattern: "established narrative vs new evidence",
    contentStructure: "what we thought we knew → the discovery that changed everything → the evidence → implications for history → unanswered questions",
    keyInsight: "Challenging established academic consensus taps into viewers' innate distrust of authority",
    viralFactor: "Mystery of ancient capabilities + 'experts were wrong' narrative = conspiracy-adjacent curiosity without misinformation",
    estimatedViews: "13M+",
    tone: ["educational", "mysterious", "thought-provoking"],
  },
  {
    id: "vc_hist_002",
    title: "The Day That Almost Ended Human Civilization (You've Never Heard of It)",
    niche: ["history", "cold war", "near-disaster", "geopolitics"],
    topic: "historical near-disaster",
    hookType: "unknown history with massive stakes",
    hook: "In 1983, one man's decision prevented a nuclear war that would have killed billions. His name was forgotten by history. Until now.",
    storytellingPattern: "unknown hero narrative",
    contentStructure: "set the stakes (nuclear war nearly happened) → who this person was → the exact moment → the decision → why we never heard of this",
    keyInsight: "Finding unknown heroes from history gives viewers the feeling of learning a secret that most people don't know",
    viralFactor: "Massive stakes (civilizational collapse) + unknown protagonist = maximum curiosity and emotional investment",
    estimatedViews: "21M+",
    tone: ["dramatic", "educational", "emotional"],
  },

  // ── Science ──────────────────────────────────────────────────
  {
    id: "vc_sci_001",
    title: "Scientists Just Discovered Something That Changes Everything We Know About the Universe",
    niche: ["science", "physics", "astronomy", "discovery"],
    topic: "scientific discovery",
    hookType: "paradigm-shifting discovery",
    hook: "In 2024, scientists found something at the edge of the observable universe that their models say shouldn't exist. They don't have an explanation.",
    storytellingPattern: "discovery → implications → mystery",
    contentStructure: "the discovery explained simply → why it breaks current models → what scientists think it means → what it could change → the unanswered question",
    keyInsight: "When science itself is baffled, it validates viewer curiosity — 'experts don't know' is the ultimate curiosity gap",
    viralFactor: "Fundamental uncertainty + implications for existence + accessible explanation = universal fascination",
    estimatedViews: "28M+",
    tone: ["educational", "awe-inspiring", "thought-provoking"],
  },
  {
    id: "vc_sci_002",
    title: "Your Brain Is Lying to You Every Second — Here's the Proof",
    niche: ["science", "psychology", "neuroscience", "mind"],
    topic: "brain perception",
    hookType: "personal relevance + proof",
    hook: "Right now, your brain is constructing a fake reality. Everything you see, hear, and feel is a simulation your brain is running. Let me prove it.",
    storytellingPattern: "claim → interactive proof → explanation → implications",
    contentStructure: "bold claim → optical illusion/test → the neuroscience → what this means for decision making → how to use this knowledge",
    keyInsight: "Making the viewer the subject of the science creates immediate personal relevance",
    viralFactor: "Interactive element (try this) + identity-level insight (your brain lies) + practical application",
    estimatedViews: "17M+",
    tone: ["educational", "mind-blowing", "engaging"],
  },

  // ── Travel / Lifestyle ───────────────────────────────────────
  {
    id: "vc_travel_001",
    title: "I Traveled to 50 Countries — The One Thing That Surprised Me Most",
    niche: ["travel", "lifestyle", "worldview", "culture"],
    topic: "world travel insights",
    hookType: "experience distillation",
    hook: "I've now been to 50 countries across 6 continents. And the one thing I wasn't expecting? Everyone was wrong about almost everything.",
    storytellingPattern: "accumulated wisdom reveal",
    contentStructure: "the journey → top misconceptions broken down by region → the unexpected truth → how travel changed my worldview → what it teaches about home",
    keyInsight: "Single insight from massive experience creates perceived authority — 'the one thing' framing distills wisdom",
    viralFactor: "Aspirational experience + contrarian discovery + personal growth arc = maximum shareability",
    estimatedViews: "8M+",
    tone: ["inspiring", "thought-provoking", "educational"],
  },

  // ── Psychology / Mind ────────────────────────────────────────
  {
    id: "vc_psych_001",
    title: "The Psychological Trick That Makes People Like You Instantly",
    niche: ["psychology", "social skills", "relationships", "self-improvement"],
    topic: "social psychology",
    hookType: "insider technique",
    hook: "Psychologists discovered a trick that makes strangers feel like they've known you for years. You can use it starting today.",
    storytellingPattern: "reveal + explanation + application",
    contentStructure: "the technique named → the psychology behind it → real-world examples → how to use it → ethical considerations",
    keyInsight: "Social advantage framing taps into universal desire for connection and belonging",
    viralFactor: "Immediate applicability + social benefit + scientific backing = everyone shares for social currency",
    estimatedViews: "23M+",
    tone: ["educational", "practical", "engaging"],
  },
  {
    id: "vc_psych_002",
    title: "Why Intelligent People Struggle More in Life",
    niche: ["psychology", "intelligence", "self-improvement", "mental health"],
    topic: "intelligence paradox",
    hookType: "counterintuitive insight",
    hook: "Studies show that higher intelligence is actually correlated with more anxiety, more loneliness, and less happiness. Here's why.",
    storytellingPattern: "paradox exploration",
    contentStructure: "the counterintuitive finding → the research → why it happens (mechanisms) → the specific struggles → how high-intelligence people can adapt",
    keyInsight: "Counterintuitive findings about desirable traits create identity-level engagement for the target audience",
    viralFactor: "Smart viewers self-identify + validation of struggle + scientific backing = comment section gold",
    estimatedViews: "15M+",
    tone: ["thought-provoking", "educational", "validating"],
  },

  // ── Motivation / Inspiration ─────────────────────────────────
  {
    id: "vc_motiv_001",
    title: "The Story of the Man Who Lost Everything at 50 and Built a Fortune by 60",
    niche: ["motivation", "entrepreneurship", "resilience", "life story"],
    topic: "late-life success",
    hookType: "redemption story",
    hook: "At 52, he was bankrupt, divorced, and sleeping in his car. At 62, he was worth $40 million. This is not a movie. This actually happened.",
    storytellingPattern: "redemption arc",
    contentStructure: "the rock bottom → the turning point decision → the decade of rebuilding → the specific moves that worked → the lessons anyone can apply",
    keyInsight: "Stories of late success neutralize the 'too late for me' excuse that stops most people",
    viralFactor: "Maximum contrast (rock bottom vs. success) + relatable failure + hope for late starters",
    estimatedViews: "19M+",
    tone: ["inspiring", "emotional", "motivational"],
  },

  // ── Real Estate ──────────────────────────────────────────────
  {
    id: "vc_re_001",
    title: "How I Bought My First Rental Property With $5,000",
    niche: ["real estate", "investing", "passive income", "finance"],
    topic: "real estate with low capital",
    hookType: "low barrier achievement",
    hook: "Everyone says you need at least $50,000 to invest in real estate. I did it with $5,000. Here's the exact strategy I used.",
    storytellingPattern: "barrier-breaking story + step-by-step guide",
    contentStructure: "the misconception → my starting situation → the strategy discovered → step-by-step breakdown → what I'd do differently → how you can do it",
    keyInsight: "Removing the 'I don't have enough money' objection is the most powerful way to convert viewers to action",
    viralFactor: "Accessible entry point + specific method + before/after proof = maximum aspiration activation",
    estimatedViews: "11M+",
    tone: ["educational", "motivational", "practical"],
  },

  // ── Food / Nutrition ─────────────────────────────────────────
  {
    id: "vc_food_001",
    title: "The Food Industry's Biggest Lie About What's Actually Healthy",
    niche: ["health", "nutrition", "food industry", "wellness"],
    topic: "food industry deception",
    hookType: "exposé / whistleblower",
    hook: "The food labeled 'healthy' in your grocery store is making you sick. And the companies selling it know exactly what they're doing.",
    storytellingPattern: "exposé narrative",
    contentStructure: "the deceptive products → what the labels actually mean → the science they hide → how to read labels correctly → the actually healthy alternatives",
    keyInsight: "Corporate malfeasance narratives create righteous anger that drives massive sharing",
    viralFactor: "Villain (food companies) + victim (viewer/public health) + actionable defense = high emotional engagement",
    estimatedViews: "24M+",
    tone: ["provocative", "educational", "empowering"],
  },

  // ── Environment / Climate ────────────────────────────────────
  {
    id: "vc_env_001",
    title: "The Simple Change That Could Save the Ocean (and Why Nobody's Doing It)",
    niche: ["environment", "climate", "ocean", "sustainability"],
    topic: "ocean conservation",
    hookType: "solution with systemic barrier",
    hook: "There's a proven solution that could clean up 90% of ocean plastic. It costs almost nothing. So why isn't anyone doing it?",
    storytellingPattern: "solution exists but is blocked",
    contentStructure: "the scale of the problem → the solution that exists → why it's not being implemented → who benefits from inaction → what individuals can do",
    keyInsight: "Actionable solutions to systemic problems convert hopelessness into engagement and sharing",
    viralFactor: "Simple solution + systemic villain + call to action = massive climate-concerned audience engagement",
    estimatedViews: "9M+",
    tone: ["educational", "hopeful", "call-to-action"],
  },

  // ── Mindset / Philosophy ─────────────────────────────────────
  {
    id: "vc_mind_001",
    title: "The Mindset Shift That Changed My Life in 24 Hours",
    niche: ["mindset", "philosophy", "self-improvement", "psychology"],
    topic: "mindset transformation",
    hookType: "rapid transformation claim",
    hook: "I learned one thing at 2 AM that changed everything about how I see life, work, and relationships. It took me 24 hours to fully implement.",
    storytellingPattern: "epiphany story",
    contentStructure: "the moment of discovery → what the mindset shift was → how it changed specific areas → the science behind it → how viewers can apply it today",
    keyInsight: "The '24-hour' timeframe creates urgency and makes the transformation feel achievable",
    viralFactor: "Speed of transformation + specific timeframe + universal application = aspirational shareability",
    estimatedViews: "12M+",
    tone: ["inspirational", "thought-provoking", "personal"],
  },
  {
    id: "vc_mind_002",
    title: "Stoicism: The Ancient Philosophy That's Taking Over Silicon Valley",
    niche: ["philosophy", "mindset", "stoicism", "productivity", "tech"],
    topic: "stoicism",
    hookType: "trend + timeless wisdom",
    hook: "The philosophy that helped Roman emperors run an empire is now the secret weapon of the world's most successful CEOs. And you've probably never studied it.",
    storytellingPattern: "ancient wisdom meets modern application",
    contentStructure: "who practices it today and why → the core principles explained simply → how to apply each principle → common misunderstandings → getting started",
    keyInsight: "Bridging ancient wisdom with modern success stories creates both credibility and relevance",
    viralFactor: "Elite association (CEOs, emperors) + practical wisdom + timeless = cross-demographic appeal",
    estimatedViews: "16M+",
    tone: ["educational", "inspiring", "philosophical"],
  },
];
